# Generated by Django 4.0.4 on 2022-06-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_remove_category_user_category_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
